swagger: '2.0'
info:
  description: This is a API Spec for testing
  version: "1"
  title: Country Api
  contact:
    email: wlyem1223@gmail.com
host: "ninth-park-223107.appspot.com"
schemes:
 - https
 - http
tags:
- name: developers
  description: Operations available to regular developers

paths:
  /api/{country}:
    get:
      tags:
      - developers
      summary: Retrieve User Country
      operationId: Get Country
      description: Get User Country Information
      consumes:
      - application/json
      parameters:
        - in: path
          name: country
          type: string
          description: user country
          required: true
      responses:
        200:
          description: User Found
          schema:
            $ref: '#/definitions/UserStatusResponse'

definitions:
  UserStatusResponse:
    type: object
    properties:
      country: 
        type: string
        example: Malaysia
      independence: 
        type: boolean
        example: true
security:
- api_key: []
securityDefinitions:
  # This section configures basic authentication with an API key.
  api_key:
    type: "apiKey"
    name: "key"
    in: "query"
  # This section configures authentication using Google API Service Accounts
  # to sign a json web token. This is mostly used for server-to-server
  # communication.
  google_jwt:
    authorizationUrl: ""
    flow: "implicit"
    type: "oauth2"
    # This must match the 'iss' field in the JWT.
    x-google-issuer: "jwt-client.endpoints.sample.google.com"
    # Update this with your service account's email address.
    x-google-jwks_uri: "https://www.googleapis.com/service_accounts/v1/jwk/YOUR-SERVICE-ACCOUNT-EMAIL"
    # This must match the "aud" field in the JWT. You can add multiple
    # audiences to accept JWTs from multiple clients.
    x-google-audiences: "echo.endpoints.sample.google.com"
  # This section configures authentication using Google OAuth2 ID Tokens.
  # ID Tokens can be obtained using OAuth2 clients, and can be used to access
  # your API on behalf of a particular user.
  google_id_token:
    authorizationUrl: ""
    flow: "implicit"
    type: "oauth2"
    x-google-issuer: "https://accounts.google.com"
    x-google-jwks_uri: "https://www.googleapis.com/oauth2/v3/certs"
    # Your OAuth2 client's Client ID must be added here. You can add
    # multiple client IDs to accept tokens from multiple clients.
    x-google-audiences: "YOUR-CLIENT-ID"    
      


